#!/usr/bin/env python3
"""Deterministic offline Unicode table generator. No third-party Python packages."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "third_party/unicode"
OUTPUT = ROOT / "crates/terminal/src/tables.rs"
GCB = {name: i for i, name in enumerate(
    ["Other", "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator",
     "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT"])}


def records(name):
    for line in (DATA / "18.0.0" / name).read_text().splitlines():
        value = line.split("#")[0].strip()
        if value:
            yield [part.strip() for part in value.split(";")]


def generate():
    manifest = json.loads((DATA / "manifest.json").read_text())
    for name, info in manifest["files"].items():
        if hashlib.sha256((DATA / name).read_bytes()).hexdigest() != info["sha256"]:
            raise ValueError(f"Unicode input changed: {name}")
    props = [0] * 0x110000

    def apply(code, bits):
        bounds = code.split("..")
        start, end = int(bounds[0], 16), int(bounds[-1], 16)
        assert 0 <= start <= end < len(props)
        for i in range(start, end + 1):
            props[i] |= bits

    for code, property_name in records("GraphemeBreakProperty.txt"):
        apply(code, GCB[property_name])
    for record in records("DerivedCoreProperties.txt"):
        if record[1] == "InCB":
            apply(record[0], {"Consonant": 1, "Linker": 2, "Extend": 3}[record[2]] << 4)
        elif record[1] == "Default_Ignorable_Code_Point":
            apply(record[0], 1 << 10)
    for code, property_name in records("emoji-data.txt"):
        if property_name in ("Extended_Pictographic", "Emoji_Presentation"):
            apply(code, 1 << (6 if property_name == "Extended_Pictographic" else 7))
    for code, property_name in records("EastAsianWidth.txt"):
        if property_name in ("W", "F", "A"):
            apply(code, 1 << (9 if property_name == "A" else 8))
    for record in records("emoji-variation-sequences.txt"):
        code, selector = record[0].split()
        assert selector in ("FE0E", "FE0F")
        apply(code, 1 << 11)
    rows = []
    start = 0
    for end in range(1, len(props) + 1):
        if end == len(props) or props[start] != props[end]:
            if props[start]:
                rows.append(f"    (0x{start:X}, 0x{end - 1:X}, 0x{props[start]:X}),")
            start = end
    result = "// Generated by scripts/generate-unicode.py; do not edit.\n"
    result += "// Unicode 18.0.0 data © Unicode, Inc.; see third_party/unicode/LICENSE.txt.\n"
    result += "#[rustfmt::skip]\npub(crate) const PROPERTIES: &[(u32, u32, u16)] = &[\n"
    return result + "\n".join(rows) + "\n];\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = generate()
    if args.check:
        if OUTPUT.read_text() != data:
            raise SystemExit("generated Unicode tables differ; regenerate and review")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(data)
    print("Unicode 18.0.0 hashes and generated tables verified")


if __name__ == "__main__":
    main()
